### ISSUE TITLE
Solve Infinity/-Infinity issue in Visual wdget

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#194]
Sometimes this shows up Cell Visual widget:

![selection_722](https://cloud.githubusercontent.com/assets/1556687/9389986/2e1d6038-4766-11e5-94ef-8a186023020f.jpg)

e.g. http://opensourcebrain.org/projects/acnet2?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FACnet2%2Fmaster%2FneuroConstruct%2FgeneratedNeuroML2%2Fpyr_4_sym.cell.nml

**Comment by adrianq** [comment]
This issue has been fixed in the last release. I was aware of it but I can't reproduce it any more.  @pgleeson I am closing this issue but if you see this problem again just let me know the model

**Comment by adrianq** [comment]
Murphy law... I have just found a model where this is happening...Move to 'In progress' again

**Comment by adrianq** [comment]
I have created a [PR for Geppetto](https://github.com/openworm/org.geppetto.frontend/pull/342) that fix this and other issues

**Comment by pgleeson** [comment]
![selection_734](https://cloud.githubusercontent.com/assets/1556687/10101156/b3495eee-638e-11e5-8041-b3593ae18589.jpg)

http://opensourcebrain.org/projects/hodgkin-huxley-tutorial/repository/revisions/master/show/Tutorial/Source?explorer=https%3A%2F%2Fraw.githubusercontent.com%2Fopenworm%2Fhodgkin_huxley_tutorial%2Fmaster%2FTutorial%2FSource%2FHHCellNetwork.net.nml

Still getting this. May be to do with not all segmentGroups (all/dend_group etc.) being present in some files..?

https://github.com/openworm/hodgkin_huxley_tutorial/blob/master/Tutorial/Source/hhcell.cell.nml

**Comment by pgleeson** [comment]
Or possibly a missing segmentGroup "all"...

**Comment by adrianq** [comment]
This is done. If you look at my comment above you can see that I created a [PR](https://github.com/openworm/org.geppetto.frontend/pull/342) for Geppetto. The PR hasn't been merged as Geppetto hasn't released yet. This time I have done a quick release in OSB so that we have some layout improvement. I will do another one once Geppetto is released.
